// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBItIVYQ004eKI0yduT2lYVobtu1zEtPYM',
    appId: '1:1071005211039:web:ef3e3366771487fe6445aa',
    messagingSenderId: '1071005211039',
    projectId: 'hometouch-bb163',
    authDomain: 'hometouch-bb163.firebaseapp.com',
    storageBucket: 'hometouch-bb163.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvzkoLCmzVWEso47KB3Hfnzq0TxAnJH0I',
    appId: '1:1071005211039:android:0dcf19af0d5d90ba6445aa',
    messagingSenderId: '1071005211039',
    projectId: 'hometouch-bb163',
    storageBucket: 'hometouch-bb163.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzMxDGW3ooFhCDX3AbPzB6mlnHDAtsTEA',
    appId: '1:1071005211039:ios:f483ee718bf890e86445aa',
    messagingSenderId: '1071005211039',
    projectId: 'hometouch-bb163',
    storageBucket: 'hometouch-bb163.firebasestorage.app',
    iosBundleId: 'com.example.hometouch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzMxDGW3ooFhCDX3AbPzB6mlnHDAtsTEA',
    appId: '1:1071005211039:ios:f483ee718bf890e86445aa',
    messagingSenderId: '1071005211039',
    projectId: 'hometouch-bb163',
    storageBucket: 'hometouch-bb163.firebasestorage.app',
    iosBundleId: 'com.example.hometouch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBItIVYQ004eKI0yduT2lYVobtu1zEtPYM',
    appId: '1:1071005211039:web:1120cce093203ce86445aa',
    messagingSenderId: '1071005211039',
    projectId: 'hometouch-bb163',
    authDomain: 'hometouch-bb163.firebaseapp.com',
    storageBucket: 'hometouch-bb163.firebasestorage.app',
  );
}
